### ISSUE TITLE
Nouvelle page : FAQ

### ISSUE THREAD

**Issue by fcamblor** [bdxio/bdxio.github.io#15]
C'est une page qui est référencée par le CFP

Elle devrait lister : 

**Les différentes typologies de talk**

| Type | Durée | Lieu | Quand | Nb slots prévus | Description |
| --- | --- | --- | --- | --- | --- |
| Conférence | 50m (Q&A incluses) | Amphis (~150pers) | Matin & AM | 20-24 | Présentation magistrale sur un sujet donné |
| Quickie | 15m | Amphis (~150pers) | Entre midi et 2 | 16-20 | Présentation rapide/éclair, discussions, sur un sujet donné |
| Hand's on | 1h 50m | Salle de TD (~30pers) | Matin & AM | 3 | Atelier où les participants ont un laptop et peuvent coder en même temps que le speaker |

**Les modalités pour les speakers**
- Place offerte
- Défraiement par type de talk
- Repas des speakers

**Comment by fcamblor** [comment]
Quelques trucs à mettre en plus :
- Réserve de places Early bird pour les participants au CFP : pas besoin d'acheter votre place, on vous en réservera des Early bird

**Comment by fcamblor** [comment]
Faire apparaître une procédure de réaffectation de place (il faudrait mettre en place un google form pour ça en se basant sur [la spreadsheet de l'année dernière (onglet "transfert place")](https://docs.google.com/spreadsheets/d/1atI4l8lPYJVs4OLme0d3z7MNclb1KwZgo05tPY9pFt0/edit#gid=0))

**Comment by josselinauguste** [comment]
On m'a demandé le processus de sélection des talks, ça aurait bien sa place dans la faq aussi

**Comment by fcamblor** [comment]
Je suis d'accord

J'ai également pensé a d'autres trucs :
- Pas besoin d'imprimer les billets (pour les participants), nécessité par contre d'arriver avec une carte étudiant (si place étudiant achetée)
- Précisions sur le défraiement : pas d'annonce pour le moment, on attend d'avoir plus de visibilité sur nos sponsors et sur le nombre de speakers non bordelais sélectionnés. A titre informatif, en 2014, nous avions défrayé les speakers non bordelais à hauteur de 75 euros (sur hotel et/ou transport).

**Comment by walien** [comment]
FAQ mise à jour avec : 
### Speaker
- Modalités de participation des speakers
- Typologies de talks
- Reserve Early Bird
- CFP

### Participant
- Procédure de transfert de place 
- Lien vers la billeterie
- "Pour les étudiants, une carte d'étudiant sera demandée à l'entrée de la conférence. 
D'autre part, il ne sera pas nécessaire pour vous d'imprimer les billets."

### Jury
- Procédure de selection

Pour la procédure de transfert de place, j'ai créé un GForm (Billeterie/2015) avec les infos qui me semblaient nécessaires, n'hésitez pas s'il vous parait incomplet.

**Comment by fcamblor** [comment]
Rajouter une section sur l'éligibilité à la formation (il n'y en a pas) : nouveauté du CPF + condition d'éligibilité à ce dernier compliquées
